service: sls-groundtruth-input

provider:
  name: aws
  runtime: python2.7

stage: ${opt:stage, 'dev'}
region: ${opt:stage, 'eu-west-1'}

functions:
  groundtruth-pre-labeling:
    handler: preLabeling.lambda_handler

  groundtruth-post-labeling:
    handler: postLabeling.lambda_handler
